version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command: "/bin/bash docker/start.sh"
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
        - "8081:80"